---
# This workflow will do a clean install of node dependencies,
# build the source code and run tests across different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SC Docker tests pipeline

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name to release ex. 4.9.1-rc0'
        required: true

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  DIST_TAG: ${{ inputs.version }}

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Start Sauce Connect
        run: |
          cp test/sc-test.yaml /tmp/sc-test.yaml
          docker run \
            -e SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }} \
            -e SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }} \
            -v /tmp:/tmp \
            --network="host" \
            -t saucelabs/sauce-connect:${DIST_TAG} \
            -c /tmp/sc-test.yaml \
            -i sc-${DIST_TAG}-$GITHUB_RUN_NUMBER &
          ./test/wait-for-sc.sh

      - name: Run Test
        run: npm run test

      - name: DockerHub Login
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Image Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker push saucelabs/sauce-connect:${DIST_TAG}

      - name: Upload generated Dockerfiles
        uses: actions/upload-artifact@v2
        with:
          name: dockerfiles
          path: dist/
